import { test, expect, describe } from "vitest";

describe("Supabase Migration Bridge Interceptor", () => {
  const checkMigration = (text: string) => {
    const textLower = text.toLowerCase();
    const isClaiming = textLower.includes("create table") || textLower.includes("alter table") || textLower.includes("drop table") || textLower.includes("create index") || textLower.includes("create type") || textLower.includes("create schema") || textLower.includes("migra") || textLower.includes("migration");
    
    if (!isClaiming) return null;
    
    const sqlMatches = text.match(/```sql[^\n]*\n([\s\S]*?)(?:```|$)/i);
    if (!sqlMatches) return null;
    
    const sql = sqlMatches[1].trim();
    const sqlLower = sql.toLowerCase();
    if (sql && !sqlLower.startsWith("select ") && (sqlLower.includes("create ") || sqlLower.includes("alter ") || sqlLower.includes("drop "))) {
      return sql;
    }
    return null;
  };

  test("A. Resposta normal contendo SQL DDL válido", () => {
    const text = "Migração:\n```sql\nCREATE TABLE a (id int);\n```";
    expect(checkMigration(text)).toBe("CREATE TABLE a (id int);");
  });

  test("D. Texto antes + SQL + texto depois", () => {
    const text = "Vou criar a tabela.\n```sql\nCREATE TABLE b (id int);\n```\nQualquer dúvida avise.";
    expect(checkMigration(text)).toBe("CREATE TABLE b (id int);");
  });

  test("E. Resposta sem SQL", () => {
    const text = "A tabela foi criada com sucesso, posso ajudar com algo mais?";
    expect(checkMigration(text)).toBeNull();
  });

  test("F. SELECT simples", () => {
    const text = "Aqui estão os dados:\n```sql\nSELECT * FROM users;\n```";
    expect(checkMigration(text)).toBeNull();
  });

  test("H. CREATE TABLE + ALTER TABLE ENABLE ROW LEVEL SECURITY", () => {
    const text = "```sql\ncreate table test (id int);\nalter table test enable row level security;\n```";
    expect(checkMigration(text)).toBe("create table test (id int);\nalter table test enable row level security;");
  });

  test("N. Markdown SQL com diferenças de capitalização", () => {
    const text = "```SQL\nCREATE TABLE c (id int);\n```";
    expect(checkMigration(text)).toBe("CREATE TABLE c (id int);");
  });

  test("O. SQL com espaços/quebras de linha diferentes", () => {
    const text = "```sql  \r\n\n  CREATE TABLE d (id int);\n\n```";
    expect(checkMigration(text)).toBe("CREATE TABLE d (id int);");
  });

  test("S. Resposta após QuestionCard com conteúdo completo (bug real)", () => {
    const text = `Aqui está a migração proposta para criar a tabela \`test_nekoai\`:

\`\`\`sql
create table test_nekoai (
  id bigint primary key generated by default as identity,
  nome text not null,
  created_at timestamptz default now()
);

alter table test_nekoai enable row level security;
\`\`\`
Observações:
- Habilitado RLS.
- Sem políticas RLS definidas.
- Nome da migração sugerido: create_test_nekoai
Quer que eu execute essa migração?`;
    expect(checkMigration(text)).toContain("create table test_nekoai");
    expect(checkMigration(text)).toContain("alter table test_nekoai enable row level security;");
  });

  test("T. Bug real do usuário: sem crase de fechamento e texto grudado", () => {
    const text = `Proposta de migração para criar a tabela \`test_nekoai\`:

**Nome da migration:** \`create_test_nekoai_table\`

\`\`\`sql
CREATE TABLE test_nekoai (
  id bigint GENERATED BY DEFAULT AS IDENTITY
  PRIMARY KEY,
  nome text NOT NULL,
  created_at timestamptz DEFAULT now()
);
Essa migration cria a tabela com as colunas solicitadas...`;
    
    const extracted = checkMigration(text);
    expect(extracted).toContain("CREATE TABLE test_nekoai");
    expect(extracted).toContain("Essa migration cria"); // Vai extrair o texto a mais também, o que é esperado para o fallback.
  });
});
