import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("neko", {
  version: () => ipcRenderer.invoke("app:version"),
  chooseProject: (options?: { defaultPath?: string }) => ipcRenderer.invoke("project:choose", options),
  getLastProjectDirectory: () => ipcRenderer.invoke("preferences:getLastProjectDirectory"),
  projectExists: (projectPath: string) => ipcRenderer.invoke("project:exists", projectPath),
  isInsideApplicationRoot: (projectPath: string) => ipcRenderer.invoke("project:isInsideApplicationRoot", projectPath),
  reportRendererError: (payload: { type: string; message: string; filename: string; lineno: number; colno: number; stack: string }) => ipcRenderer.invoke("renderer:report-error", payload),
  getThumbnail: (projectPath: string) => ipcRenderer.invoke("project:thumbnail", projectPath),
  saveThumbnail: (projectPath: string, dataUrl: string) => ipcRenderer.invoke("project:saveThumbnail", { projectPath, dataUrl }),
  getLastEdited: (projectPath: string) => ipcRenderer.invoke("project:lastEdited", projectPath),
  getRecentProjects: () => ipcRenderer.invoke("projects:getRecent"),
  touchRecentProject: (projectPath: string) => ipcRenderer.invoke("projects:touchRecent", projectPath),
  removeRecentProject: (projectPath: string) => ipcRenderer.invoke("projects:removeRecent", projectPath),
  toggleFavoriteProject: (projectPath: string) => ipcRenderer.invoke("projects:toggleFavorite", projectPath),
  saveRecentProjects: (projects: any[]) => ipcRenderer.invoke("projects:saveRecent", projects),
  detectTechnology: (projectPath: string) => ipcRenderer.invoke("projects:detectTechnology", projectPath),
  onRecentProjectsUpdated: (callback: (projects: any[]) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, data: any[]) => callback(data);
    ipcRenderer.on("recent-projects:updated", listener);
    return () => ipcRenderer.removeListener("recent-projects:updated", listener);
  },
  createProject: (projectPath: string | { projectPath: string; source?: string }, source?: string) => ipcRenderer.invoke("project:create", typeof projectPath === "string" ? { projectPath, source } : projectPath),
  openProject: (projectPath: string | { projectPath: string; source?: string }, source?: string) => ipcRenderer.invoke("project:create", typeof projectPath === "string" ? { projectPath, source } : projectPath),
  status: () => ipcRenderer.invoke("opencode:status"),
  prompt: (sessionId: string, text: string, model?: { providerID: string; modelID: string; variant?: string }, attachments?: any[], contextPaths?: string[], planMode = false, effort?: string, perf?: { t0?: number; prepMs?: number }) => ipcRenderer.invoke("opencode:prompt", { sessionId, text, model, attachments, contextPaths, planMode, effort, perf }),
  messages: (sessionId: string) => ipcRenderer.invoke("opencode:messages", sessionId),
  sessionStatus: (sessionId: string) => ipcRenderer.invoke("opencode:sessionStatus", sessionId),
  stop: (payload?: { source?: string }) => ipcRenderer.invoke("project:stop", payload),
  abort: (sessionId: string) => ipcRenderer.invoke("opencode:abort", sessionId),
  permissions: (sessionId: string) => ipcRenderer.invoke("opencode:permissions", sessionId),
  fetchPendingPermissions: (sessionId: string) => ipcRenderer.invoke("opencode:fetchPendingPermissions", sessionId),
  permissionReply: (sessionId: string, permissionId: string, response: "once" | "always" | "reject", remember = false) => ipcRenderer.invoke("opencode:permissionReply", { sessionId, permissionId, response, remember }),
  questionReply: (sessionId: string, requestId: string, answers: string[] | string[][]) => ipcRenderer.invoke("opencode:questionReply", { sessionId, requestId, answers }),
  questionReject: (sessionId: string, requestId: string) => ipcRenderer.invoke("opencode:questionReject", { sessionId, requestId }),
  tree: () => ipcRenderer.invoke("project:tree"),
  refresh: () => ipcRenderer.invoke("project:refresh"),
  checkpointTask: () => ipcRenderer.invoke("project:checkpointTask"),
  undoTask: (taskId: string) => ipcRenderer.invoke("project:undoTask", taskId),
  readFile: (relativePath: string) => ipcRenderer.invoke("project:file", relativePath),
  models: () => ipcRenderer.invoke("models:list"),
  providers: () => ipcRenderer.invoke("providers:list"),
  setModelEnabled: (providerID: string, modelID: string, enabled: boolean) => ipcRenderer.invoke("model:setEnabled", { providerID, modelID, enabled }),
  setProviderEnabled: (providerID: string, enabled: boolean) => ipcRenderer.invoke("provider:setEnabled", { providerID, enabled }),
  connectProvider: (providerID: string, key: string) => ipcRenderer.invoke("provider:connect", { providerID, key }),
  disconnectProvider: (providerID: string) => ipcRenderer.invoke("provider:disconnect", providerID),
  pickAttachments: () => ipcRenderer.invoke("attachments:pick"),
  saveClipboardImage: (dataUrl: string, mime: string) => ipcRenderer.invoke("attachments:clipboard", { dataUrl, mime }),
  attachmentsFromPaths: (paths: string[]) => ipcRenderer.invoke("attachments:paths", paths),
  searchProject: (query: string) => ipcRenderer.invoke("project:search", query),
  commands: () => ipcRenderer.invoke("commands:list"),
  runCommand: (sessionId: string, command: string, args: string, model?: { providerID: string; modelID: string }) => ipcRenderer.invoke("opencode:command", { sessionId, command, arguments: args, model }),
  startPreview: () => ipcRenderer.invoke("preview:start"),
  stopPreview: () => ipcRenderer.invoke("preview:stop"),
  refreshPreview: () => ipcRenderer.invoke("preview:refresh"),
  previewRoutes: (opts?: { force?: boolean }) => ipcRenderer.invoke("preview:routes", opts),
  previewNavigate: (routePath: string) => ipcRenderer.invoke("preview:navigate", routePath),
  setInternalPreviewOverlay: (active: boolean) => ipcRenderer.invoke("preview:internalOverlay", active),
  siteCloneAnalyze: (url: string, limits?: any) => ipcRenderer.invoke("siteClone:analyze", { url, limits }),
  siteCloneCapture: (url: string) => ipcRenderer.invoke("siteClone:capture", { url }),
  siteCloneImportAssets: (assets: { url: string; kind: string }[]) => ipcRenderer.invoke("siteClone:importAssets", { assets }),
  siteCloneCancel: () => ipcRenderer.invoke("siteClone:cancel"),
  onSiteCloneEvent: (callback: (event: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("siteclone:event", listener); return () => ipcRenderer.removeListener("siteclone:event", listener); },
  stylePreviewFrame: () => ipcRenderer.invoke("preview:styleFrame"),
  syncInternalPreview: (payload: { session: number; url: string; visible: boolean; bounds?: { x: number; y: number; width: number; height: number } }) => ipcRenderer.invoke("preview:internalSync", payload),
  openPreviewExternal: (url: string) => ipcRenderer.invoke("preview:openExternal", url),
  validateBuild: () => ipcRenderer.invoke("project:validateBuild"),
  onEvent: (callback: (event: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("opencode:event", listener); return () => ipcRenderer.removeListener("opencode:event", listener); },
  onPreviewEvent: (callback: (event: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("preview:event", listener); return () => ipcRenderer.removeListener("preview:event", listener); },
  githubStatus: (refresh = false) => ipcRenderer.invoke("github:status", refresh),
  githubStart: (forceReauthorize = false) => ipcRenderer.invoke("github:start", forceReauthorize),
  githubCancel: () => ipcRenderer.invoke("github:cancel"),
  githubDisconnect: () => ipcRenderer.invoke("github:disconnect"),
  githubOpen: (url: string) => ipcRenderer.invoke("github:open", url),
  githubGitStatus: () => ipcRenderer.invoke("github:gitStatus"),
  githubListBranches: (repoFullName: string) => ipcRenderer.invoke("github:listBranches", repoFullName),
  githubCheckoutBranch: (branchName: string) => ipcRenderer.invoke("github:checkoutBranch", branchName),
  githubCreateBranch: (name: string, baseBranch?: string) => ipcRenderer.invoke("github:createBranch", { name, baseBranch }),
  githubLinkProject: (repoFullName: string, replaceRemote = false, overwriteLocalContent = false) => ipcRenderer.invoke("github:linkProject", { repoFullName, replaceRemote, overwriteLocalContent }),
  githubChooseCloneDestination: () => ipcRenderer.invoke("github:chooseCloneDestination"),
  githubOpenFolder: (folderPath: string) => ipcRenderer.invoke("github:openFolder", folderPath),
  githubCloneProject: (repoFullName: string, parentPath?: string, projectName?: string) => ipcRenderer.invoke("github:cloneProject", { repoFullName, parentPath, projectName }),
  githubPublishProject: (repoName: string, isPrivate = true) => ipcRenderer.invoke("github:publishProject", { repoName, private: isPrivate }),
  githubCancelPublish: () => ipcRenderer.invoke("github:cancelPublish"),
  githubAutoCommitTask: (payload?: { projectPath?: string; taskId?: string; message?: string } | string, legacyMessage?: string) => {
    if (typeof payload === "string") {
      return ipcRenderer.invoke("github:autoCommitTask", { taskId: payload, message: legacyMessage });
    }
    return ipcRenderer.invoke("github:autoCommitTask", payload || {});
  },
  githubGetAutoCommit: (projectPath?: string) => ipcRenderer.invoke("github:getAutoCommit", projectPath),
  githubSetAutoCommit: (projectPath: string, enabled: boolean) => ipcRenderer.invoke("github:setAutoCommit", { projectPath, enabled }),
  githubGetDefaultBranch: () => ipcRenderer.invoke("github:getDefaultBranch"),
  githubCommitPush: (message: string) => ipcRenderer.invoke("github:commitPush", { message }),
  githubCreatePullRequest: (repoFullName: string, head: string, base: string, title: string, body: string) => ipcRenderer.invoke("github:createPullRequest", { repoFullName, head, base, title, body }),
  githubDiscardChanges: () => ipcRenderer.invoke("github:discardChanges"),
  githubUnlinkProject: () => ipcRenderer.invoke("github:unlinkProject"),
  githubCheckRepoAccess: (repoFullName: string) => ipcRenderer.invoke("github:checkRepoAccess", repoFullName),
  onGithubEvent: (callback: (event: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("github:event", listener); return () => ipcRenderer.removeListener("github:event", listener); },
  supabaseGetState: () => ipcRenderer.invoke("supabase:get-state"),
  supabaseConnectWithToken: (token: string) => ipcRenderer.invoke("supabase:connect-with-token", token),
  supabaseRefreshProjects: (clearNotice?: boolean) => ipcRenderer.invoke("supabase:refresh-projects", clearNotice),
  supabaseCreateProject: (payload: { name: string; orgId: string; dbPassword: string; region: string }) => ipcRenderer.invoke("supabase:create-project", payload),
  supabaseSelectProject: (ref: string) => ipcRenderer.invoke("supabase:select-project", ref),
  supabaseDisconnect: () => ipcRenderer.invoke("supabase:disconnect"),
  supabaseUnlink: () => ipcRenderer.invoke("supabase:unlink"),
  supabaseOpenTokenPage: () => ipcRenderer.invoke("supabase:open-token-page"),
  supabaseOpenDashboard: () => ipcRenderer.invoke("supabase:open-dashboard"),
  supabaseReplyMigration: (payload: { proposalId: string; approved: boolean }) => ipcRenderer.invoke("supabase:reply-migration", payload),
  supabaseGetPendingMigration: (sessionId: string) => ipcRenderer.invoke("supabase:get-pending-migration", sessionId),
  onSupabaseStateChange: (callback: (state: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("supabase:state-changed", listener); return () => ipcRenderer.removeListener("supabase:state-changed", listener); },
  onSupabaseMigrationEvent: (callback: (event: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("supabase:migration-event", listener); return () => ipcRenderer.removeListener("supabase:migration-event", listener); },
  vercelGetState: () => ipcRenderer.invoke("vercel:get-state"),
  vercelDetectProject: (gitRepoOverride?: string) => ipcRenderer.invoke("vercel:detect-project", gitRepoOverride),
  vercelConnect: () => ipcRenderer.invoke("vercel:connect"),
  vercelCancelLogin: () => ipcRenderer.invoke("vercel:cancel-login"),
  vercelDisconnect: () => ipcRenderer.invoke("vercel:disconnect"),
  vercelUnlink: () => ipcRenderer.invoke("vercel:unlink"),
  vercelRequestLinkIntent: (detectedProjectId?: string) => ipcRenderer.invoke("vercel:request-link-intent", detectedProjectId),
  vercelUseDetectedProject: (payload: { intentId: string }) => ipcRenderer.invoke("vercel:use-detected-project", payload),
  vercelRequestPublishIntent: (projectName?: string) => ipcRenderer.invoke("vercel:request-publish-intent", projectName),
  vercelPublish: (payload?: { intentId?: string; customProjectName?: string } | string) => ipcRenderer.invoke("vercel:publish", payload),
  vercelOpenDeployment: () => ipcRenderer.invoke("vercel:open-deployment"),
  vercelOpenDashboard: () => ipcRenderer.invoke("vercel:open-dashboard"),
  onVercelStateChange: (callback: (state: any) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data); ipcRenderer.on("vercel:state-changed", listener); return () => ipcRenderer.removeListener("vercel:state-changed", listener); },
  onVercelLog: (callback: (message: string) => void) => { const listener = (_event: Electron.IpcRendererEvent, data: string) => callback(data); ipcRenderer.on("vercel:log", listener); return () => ipcRenderer.removeListener("vercel:log", listener); },
  licenseGetState: () => ipcRenderer.invoke("license:get-state"),
  licenseActivate: (licenseKey: string) => ipcRenderer.invoke("license:activate", { licenseKey }),
  licenseResetDevice: (licenseKey: string) => ipcRenderer.invoke("license:reset-device", { licenseKey }),
  licenseValidate: () => ipcRenderer.invoke("license:validate"),
  licenseDeactivate: (licenseId?: string) => ipcRenderer.invoke("license:deactivate", { licenseId }),
  onLicenseStateChange: (callback: (state: any) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data);
    ipcRenderer.on("license:state-changed", listener);
    return () => ipcRenderer.removeListener("license:state-changed", listener);
  },
  updaterGetState: () => ipcRenderer.invoke("updater:get-state"),
  updaterCheck: () => ipcRenderer.invoke("updater:check"),
  updaterDownload: () => ipcRenderer.invoke("updater:download"),
  updaterInstall: () => ipcRenderer.invoke("updater:install"),
  onUpdaterStateChange: (callback: (state: any) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data);
    ipcRenderer.on("updater:state-changed", listener);
    return () => ipcRenderer.removeListener("updater:state-changed", listener);
  },
  lovableGetState: () => ipcRenderer.invoke("lovable:get-state"),
  lovableOpenLogin: () => ipcRenderer.invoke("lovable:open-login"),
  lovableLinkProject: (projectId?: string) => ipcRenderer.invoke("lovable:link-project", projectId),
  lovableUnlink: () => ipcRenderer.invoke("lovable:unlink"),
  lovableTestConnection: () => ipcRenderer.invoke("lovable:test-connection"),
  onLovableStateChange: (callback: (state: any) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, data: any) => callback(data);
    ipcRenderer.on("lovable:state-changed", listener);
    return () => ipcRenderer.removeListener("lovable:state-changed", listener);
  },
  windowMinimize: () => ipcRenderer.invoke("window:minimize"),
  windowToggleMaximize: () => ipcRenderer.invoke("window:toggleMaximize"),
  windowIsMaximized: () => ipcRenderer.invoke("window:isMaximized"),
  windowClose: () => ipcRenderer.invoke("window:close"),
  onWindowMaximizedChange: (callback: (isMaximized: boolean) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, isMaximized: boolean) => callback(isMaximized);
    ipcRenderer.on("window:maximized-change", listener);
    return () => ipcRenderer.removeListener("window:maximized-change", listener);
  }
});


